### PR TITLE
Update BinarySensorCard to use Mushroom Chips card with default configuration

### PR DESCRIPTION
**Pull request by dipseth**

### CODE REVIEW

**Comment by dipseth** [comment]
Update Binary Sensor to use Chips card in Area Views, allowing native icons to be seen in the dashboard:

image

**Comment by dipseth** [comment]
FYI:

The third Chip, first column second row, is the result of a card option overriding the default.  This is why it isn't green, though it is in an on state.

Part of my config

```
  card_options:
    binary_sensor.office_radar:
      type: custom:mushroom-chips-card
      chips:
        - type: entity
          entity: binary_sensor.office_radar
```

**Comment by DigiLive** [comment]
Firstly, thank you for your effort.

I need some more context.
If the goal is to show the "native" icons at a binary sensor card, we can accomplish this by changing the current default icon.
This can be tested by setting a card option, E.g.:

```yaml
    card_options:
      binary_sensor.beweging_keuken_beweging:
        icon: null
```

If the goal is to change the entire appearance of the card so it looks like a chip, then we need to redefine the binary sensor class indeed.

@dipseth Please inform me about you actual goal.

**Comment by dipseth** [comment]
> Firstly, thank you for your effort.
> 
> I need some more context. If the goal is to show the "native" icons at a binary sensor card, we can accomplish this by changing the current default icon. This can be tested by setting a card option, E.g.:
> 
> ```yaml
>     card_options:
>       binary_sensor.beweging_keuken_beweging:
>         icon: null
> ```
> 
> If the goal is to change the entire appearance of the card so it looks like a chip, then we need to redefine the binary sensor class indeed.
> 
> @dipseth Please inform me about you actual goal.

I was having a hard time distinguishing all the different binary sensors without the icon, and repeating the card_options entry for every single binary sensor was not practical for me.    I usually would just use card mod, but that didn't seem to work here as there was no obvious way to adjust to style for all these entites dynamically.

So I would my motivation was definitely the latter as I think the chips card makes it slot easier to see information I'm look for faster in the area views.

**Comment by DigiLive** [comment]
> [!CAUTION]
> Do not commit any changes to this Pull Request until further notice.
> Until the discussion below has been resolved, this conversation is locked.

@AalianKhan What's your opinion in the appearance matter?
IMHO For the binary sensors, the chipscard appearance is a bit out of context with the appearances of the other cards since they are smaller and indicating the `on` state by icon/icon-color only.
I'm OK with changing the default icon.

(I think the chipscard is more ideal for scenes, as suggested at #164).

image
versus
image

If we agree on accepting the chipscard appearance, we must decide on changing the current appearance or to add the chipscard as an alternative appearance for binary sensors.

**Comment by AalianKhan** [comment]
Hey Dipseth, Thanks for your efforts!
IMO, the current appearance of the card looks decent. Just having binary sensors look different looks a bit odd to me and destroys the continuity. 

I think the best way forward is to add an option under the [domain option](https://github.com/AalianKhan/mushroom-strategy/wiki/Strategy-Options#domains) where the user can define their card style for a set domain. That way the user has control over how any domain looks which may result in some creative dashboards that auto-generate which is one of my main goals with this project.

**Comment by DigiLive** [comment]
I'll see if I can introduce a chipscard for the benefit of #135 (Request 1).
Involves PR #164.

From there we can see if we can offer the chipscard as an alternative appearance for entities.

**Pull request closed without merging**
