### PR TITLE
Add option to hide all entities of a device.

### LINKED ISSUE #48: Add option to hide all entities of a device
**Is your feature request related to a problem? Please describe.**
Enhance the feature https://github.com/AalianKhan/mushroom-strategy/issues/10 with a way to specify names via Regex

**Describe the solution you'd like**
This setting can be an option on the `entity_config` that hides entities based on a Regex

**Describe alternatives you've considered**
The alternate is to specify each and every entity that must be hidden via an individual `entity_config`

**Additional context**
Originated from https://github.com/AalianKhan/mushroom-strategy/issues/10

### PR DESCRIPTION
**Pull request by AalianKhan**
#48

### CODE REVIEW

**Comment by ajagnanan** [comment]
Would it be better to have it under a separate `device_options` instead of nested in `card_options`?

**Comment by AalianKhan** [comment]
@ajagnanan How I see it is that card_options is for editing the display of the cards. Entity IDs and now device IDs are just specifiers for which card to edit. I didn't want to create another entry for just hiding devices.

**Comment by ajagnanan** [comment]
Gotcha, I can test it when ready.

**Review by DigiLive — APPROVED** [review]

**Comment by DigiLive** [comment]
> Would it be better to have it under a separate device_options instead of nested in card_options?

> @ajagnanan How I see it is that card_options is for editing the display of the cards. Entity IDs and now device IDs are just specifiers for which card to edit. I didn't want to create another entry for just hiding devices.

The way I see it, cards are a visual representation of an <ins>entity</ins>.
So actually I'm not to sure about listing a device_ids among entity_ids.

**Comment by DigiLive** [comment]
> Gotcha, I can test it when ready.

@ajagnanan You can always test code.

1. Make sure you create a backup of the original files to be able to revert.

2. Place file `src\mushroom-strategy.js` from the correct branch (in this case `hide-devices`) in folder `config/www/community/mushroom-strategy/` of your HA instance.

3. Remove file `mushroom-strategy.tar.gz` from folder `config/www/community/mushroom-strategy/` of your HA instance.

**Comment by AalianKhan** [comment]
@DigiLive Cards can display anything from areas to devices. It is a bit of a subjective statement

**Comment by DigiLive** [comment]
> @DigiLive Cards can display anything from areas to devices. It is a bit of a subjective statement

No they can't, unless when it's a template-card of some sort. Otherwise cards display (or behave) on entity properties.
But I see you've made your decision already by merging, so no need to discuss it anymore. 👍🏻
It's fine with me. Just giving feedback to show other perspectives.

**Pull request merged**
