### PR TITLE
Vacuum cards

### PR DESCRIPTION
**Pull request by noamblitz**
Add auto-generating vacuum cards

### CODE REVIEW

**Comment by noamblitz** [comment]
Sorry for all these commits, was testing some stuff

**Review by DigiLive — COMMENTED** [review]
The added code is consistent with the code currently in main.

- Cards for entities of the vacuum domain are added to area views (If the entity has an area assigned to it).
- No additional chips.
- No additional dashboard for the vacuum domain.

**Comment by DigiLive** [comment]
@noamblitz
PR #7 is a massive code overhaul which isn't compatible with any of the code in the current main branch.
If @AalianKhan decides to add support for the vacuum domain, would you mind waiting for PR #7 to be finished?

> Sorry for all these commits, was testing some stuff

Don't worry about it.
We can squash or rebase to a single commit.

**Comment by noamblitz** [comment]
Sure! I'm currently using my fork so I'm not in a rush :).

**Comment by DigiLive** [comment]
@noamblitz Still want to contribute vacuum cards?

**Review by DigiLive — COMMENTED** [review]
Based on old code. Has to be re-implemented.

**Pull request closed without merging**
