### PR TITLE
Add Magic areas

### PR DESCRIPTION
**Pull request by AalianKhan**
#16 and #32

### CODE REVIEW

**Comment by AalianKhan** [comment]
@DigiLive should I move this code to the area card instead?

**Review by DigiLive — CHANGES_REQUESTED** [review]
The responsibility of class `AreaCard` is is to create a card.
The responsibility of class `HomeView` is to get a card, created by class `AreaCard`.

So, I think, the current location of your changes, are in the wrong place.

Also, don't do things like this:

```js
if (!(temperature || humidity || lux)) {
  ...
}
if (temperature || humidity || lux) {
  ...
}
```

**Comment by DigiLive** [comment]
Replaced by #75

**Comment by DigiLive** [comment]
@AalianKhan Can you decide on deleting the `magic-areas` branch?

**Pull request closed without merging**
