### PR TITLE
Refactor readme to point to wiki

### PR DESCRIPTION
**Pull request by AalianKhan**
Please also check the wiki to look for any mistakes

### CODE REVIEW

**Review by DigiLive — COMMENTED** [review]
My comments below are my personal opinion.
Don't shoot me if you disagree ;).

Remove line 19..21.
It's too "personal and humble", especially now the strategy is evolving.

Describe what the strategy does and does not, like how you started at the features section.
E.g.

- It generates a view for this and that.
- It generates an overview of this and that.
- Lots of options.

Does not
- create a (yaml configuration for a) mushroom dashboard. (Although I think this is possible)

Mention the places to get help. Something like...
For help or assistance visit the [wiki](https://github.com/AalianKhan/mushroom-strategy/wiki) and [discussions](https://github.com/AalianKhan/mushroom-strategy/discussions).
Having issues/ideas, report them at [issues](https://github.com/AalianKhan/mushroom-strategy/issues).

Place the images below the text.

Mention [HACS](https://hacs.xyz/). Users can stumble upon this repo in different ways.
Mentioning HACS lowers the bar to try-out/install the strategy.
The readme should persuade users to use the strategy.

**Comment by DigiLive** [comment]
About the Wiki:

Since wiki by itself don't work with reviews or PR's, maybe we should use a construction like described at https://nimblehq.co/blog/create-github-wiki-pull-request.
This might also come in handy if a PR requires changes to the wiki.

1. `[hacsUrl]` is undefined for https://github.com/AalianKhan/mushroom-strategy/wiki#hacs.
   Also, keep in mind HACS 2.0 is coming soon and offered to users as a beta.
   It has another interface which don't match your current instructions.

2. HACS is spelled like HACs at https://github.com/AalianKhan/mushroom-strategy/wiki#basic-setup
   Also, you could suggest to redownload the package with hacs besides the instruction to manually adding the reference.

3. The link to Card Options at https://github.com/AalianKhan/mushroom-strategy/wiki/Adding-and-Hiding-entities-and-devices#hidding-specific-entities-and-devices doesn't work.

4. At https://github.com/AalianKhan/mushroom-strategy/wiki/Strategy-Options#views:
   _"All devices that are in an area where hidden is set to false/undefined are shown*"_ might be clearer when it's _"Devices of a hidden area are excluded from the view. See [Areas](https://github.com/AalianKhan/mushroom-strategy/wiki/Strategy-Options#areas)."_

5. At https://github.com/AalianKhan/mushroom-strategy/wiki/Strategy-Options#chips:
   _"All devices that are in an area where hidden is set to false/undefined are counted."_ might be clearer when it's _"Devices of a hidden area are excluded from the count."_
  `[mushroom-chipsUrl]` is undefined for https://github.com/piitaya/lovelace-mushroom/blob/main/docs/cards/chips.md.
   Maybe tell we try to use the default weather entity if it's not defined here.

**Comment by AalianKhan** [comment]
Once again, Thank you very much for your very constructive feedback. I am gonna set the Wiki pull request soon.

**Comment by DigiLive** [comment]
@AalianKhan Maybe you want some of the changes of https://github.com/AalianKhan/mushroom-strategy/commit/c3047bbc003c9f770099b2302672cb9976c7564a also.

I had these changes ready before this PR came out. 😅

**Comment by DigiLive** [comment]
Changes are included in #81

**Comment by DigiLive** [comment]
@AalianKhan Can you decide on deleting the `Move-docs-to-Wiki` branch?
The Wiki should be up to date at this moment.

**Pull request closed without merging**
