### PR TITLE
Add Magic areas + chips

### PR DESCRIPTION
**Pull request by adrienbrault**
Hey,

This includes #75, with the addition of chips for lights, climate, motion and media players.

Here's what it looks like:

This is a start, WDYT?

### CODE REVIEW

**Comment by DigiLive** [comment]
Tanks you for your effort :)

So, if I understand correctly...
This PR replaces #75 which replaces #44?
The other two can be closed?

Could you please add doc-blocks for the added functions/methods, comments to explain the purpose of the pieces of code and also refactor variable/property names into more descriptive ones. E.g. `const lock = ...` into `const lockId = ...`

PS: Don't push content of the `dist` directory. It will create a merge conflict.

**Comment by adrienbrault** [comment]
> So, if I understand correctly... This PR replaces #75 which replaces #44? The other two can be closed?

#75 does replace #44.

And this one includes the commits from #75.
But I'd rather get #75 merged first, since #76 isn't quite ready yet IMHO. 

Specifically, this MR adds 2 new requirements:
- https://github.com/ofekashery/vertical-stack-in-card
- https://github.com/thomasloven/lovelace-card-mod

And I wish the AreaCard could automatically create a chip for all lights/media_players/etc, without requiring a group to be configured.

> Could you please add doc-blocks for the added functions/methods, comments to explain the purpose of the pieces of code and also refactor variable/property names into more descriptive ones. E.g. `const lock = ...` into `const lockId = ...`
> 
> PS: Don't push content of the `dist` directory. It will create a merge conflict.

Noted, I will, on #75 first ;-) !

**Comment by DigiLive** [comment]
> [!WARNING]
> The `main` branch has been switched to TypeScript.
> Update your feature branch accordingly!

**Comment by adrienbrault** [comment]
Hey, closing as I won't be working more on this implementation.

I am exploring a different approach: https://github.com/adrienbrault/ha-jsx-strategy

**Pull request closed without merging**
